# Generated by Django 5.1.2 on 2024-10-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bottle_volume_ml',
            field=models.FloatField(),
        ),
    ]
